# Generated by Django 4.0.4 on 2024-07-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_certification_remove_project_technology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.ImageField(null=True, upload_to='certifications/'),
        ),
    ]
