# Generated by Django 4.0.4 on 2024-07-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_skill_post_image_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='online',
            field=models.URLField(blank=True, null=True),
        ),
    ]
